[theme]
# Primary color for interactive elements
primaryColor = "#FF6B6B"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Max file size for uploads (in MB)
maxUploadSize = 200

# Max message size (in MB)
maxMessageSize = 200

[browser]
# Whether to send usage statistics to Streamlit
gatherUsageStats = false

# Server address
serverAddress = "localhost"

# Port
serverPort = 8501